version: '3.8'

services:
  backend:
    build: ./backend
    container_name: job_scraper_backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    platform: linux/amd64
    container_name: job_scraper_frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"